//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ban : IEntity
    {
        public long gameId { get; set; }
        public int teamId { get; set; }
        public Nullable<short> championId { get; set; }
        public Nullable<short> pickTurn { get; set; }
    
        public virtual team team { get; set; }
    }
}
