//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class frame : IEntity
    {
        public frame()
        {
            this.gameframe = new HashSet<gameframe>();
        }
    
        public int participantFramesId { get; set; }
        public string events { get; set; }
        public Nullable<int> timestamp { get; set; }
    
        public virtual participantframes participantframes { get; set; }
        public virtual ICollection<gameframe> gameframe { get; set; }
    }
}
