//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class mastery
    {
        public int masteryId { get; set; }
        public long gameId { get; set; }
        public int participantId { get; set; }
        public Nullable<int> rank { get; set; }
    
        public virtual participant participant { get; set; }
    }
}
