//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantframes : IEntity
    {
        public int participantFramesId { get; set; }
        public int participantFrame1 { get; set; }
        public int participantFrame2 { get; set; }
        public int participantFrame3 { get; set; }
        public int participantFrame4 { get; set; }
        public int participantFrame5 { get; set; }
        public int participantFrame6 { get; set; }
        public int participantFrame7 { get; set; }
        public int participantFrame8 { get; set; }
    
        public virtual frame frame { get; set; }
        public virtual participantframe participantframe { get; set; }
        public virtual participantframe participantframe9 { get; set; }
        public virtual participantframe participantframe10 { get; set; }
        public virtual participantframe participantframe11 { get; set; }
        public virtual participantframe participantframe12 { get; set; }
        public virtual participantframe participantframe13 { get; set; }
        public virtual participantframe participantframe14 { get; set; }
        public virtual participantframe participantframe15 { get; set; }
    }
}
