//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class participantidentities
    {
        public long gameId { get; set; }
        public int accountId { get; set; }
        public Nullable<int> participantId { get; set; }
    
        public virtual game game { get; set; }
        public virtual player player { get; set; }
    }
}
