//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat : IEntity
    {
        public long gameId { get; set; }
        public int participantId { get; set; }
        public Nullable<bool> win { get; set; }
        public Nullable<int> item0 { get; set; }
        public Nullable<int> item1 { get; set; }
        public Nullable<int> item2 { get; set; }
        public Nullable<int> item3 { get; set; }
        public Nullable<int> item4 { get; set; }
        public Nullable<int> item5 { get; set; }
        public Nullable<int> item6 { get; set; }
        public Nullable<int> kills { get; set; }
        public Nullable<int> deaths { get; set; }
        public Nullable<int> assists { get; set; }
        public Nullable<int> largestKillingSpree { get; set; }
        public Nullable<int> largestMultiKill { get; set; }
        public Nullable<int> killingSprees { get; set; }
        public Nullable<int> longestTimeSpentLiving { get; set; }
        public Nullable<int> doubleKills { get; set; }
        public Nullable<int> tripleKills { get; set; }
        public Nullable<int> quadraKills { get; set; }
        public Nullable<int> pentaKills { get; set; }
        public Nullable<int> unrealKills { get; set; }
        public Nullable<int> totalDamageDealt { get; set; }
        public Nullable<int> magicDamageDealt { get; set; }
        public Nullable<int> physicalDamageDealt { get; set; }
        public Nullable<int> trueDamageDealt { get; set; }
        public Nullable<int> largestCriticalStrike { get; set; }
        public Nullable<int> totalDamageDealtToChampions { get; set; }
        public Nullable<int> magicDamageDealtToChampions { get; set; }
        public Nullable<int> physicalDamageDealtToChampions { get; set; }
        public Nullable<int> trueDamageDealtToChampions { get; set; }
        public Nullable<int> totalHeal { get; set; }
        public Nullable<int> totalUnitsHealed { get; set; }
        public Nullable<int> totalDamageTaken { get; set; }
        public Nullable<int> magicalDamageTaken { get; set; }
        public Nullable<int> physicalDamageTaken { get; set; }
        public Nullable<int> trueDamageTaken { get; set; }
        public Nullable<int> goldEarned { get; set; }
        public Nullable<int> goldSpent { get; set; }
        public Nullable<int> turretKills { get; set; }
        public Nullable<int> inhibitorKills { get; set; }
        public Nullable<int> totalMinionsKilled { get; set; }
        public Nullable<int> neutralMinionsKilled { get; set; }
        public Nullable<int> neutralMinionsKilledTeamJungle { get; set; }
        public Nullable<int> neutralMinionsKilledEnemyJungle { get; set; }
        public Nullable<int> totalTimeCrowdControlDealt { get; set; }
        public Nullable<int> champLevel { get; set; }
        public Nullable<int> visionWardsBoughtInGame { get; set; }
        public Nullable<int> sightWardsBoughtInGame { get; set; }
        public Nullable<int> wardsPlaced { get; set; }
        public Nullable<int> wardsKilled { get; set; }
        public Nullable<bool> firstBloodKill { get; set; }
        public Nullable<bool> firstBloodAssist { get; set; }
        public Nullable<bool> firstTowerKill { get; set; }
        public Nullable<bool> firstTowerAssist { get; set; }
        public Nullable<bool> firstInhibitorKill { get; set; }
        public Nullable<bool> firstInhibitorAssist { get; set; }
        public Nullable<int> combatPlayerScore { get; set; }
        public Nullable<int> objectivePlayerScore { get; set; }
        public Nullable<int> totalPlayerScore { get; set; }
        public Nullable<int> totalScoreRank { get; set; }
    
        public virtual participant participant { get; set; }
    }
}
