//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat : IEntity
    {
        public long gameId { get; set; }
        public int participantId { get; set; }
        public Nullable<bool> win { get; set; }
        public Nullable<short> item0 { get; set; }
        public Nullable<short> item1 { get; set; }
        public Nullable<short> item3 { get; set; }
        public Nullable<short> item4 { get; set; }
        public Nullable<short> item5 { get; set; }
        public Nullable<short> item6 { get; set; }
        public Nullable<short> kills { get; set; }
        public Nullable<short> deaths { get; set; }
        public Nullable<short> assists { get; set; }
        public Nullable<short> largestKillingSpree { get; set; }
        public Nullable<short> largestMultiKill { get; set; }
        public Nullable<short> killingSprees { get; set; }
        public Nullable<short> longestTimeSpentLiving { get; set; }
        public Nullable<short> doubleKills { get; set; }
        public Nullable<short> tripleKills { get; set; }
        public Nullable<short> quadraKills { get; set; }
        public Nullable<short> pentaKills { get; set; }
        public Nullable<short> unrealKills { get; set; }
        public Nullable<short> totalDamageDealt { get; set; }
        public Nullable<short> magicDamageDealt { get; set; }
        public Nullable<short> physicalDamageDealt { get; set; }
        public Nullable<short> trueDamageDealt { get; set; }
        public Nullable<short> largestCriticalStrike { get; set; }
        public Nullable<short> totalDamageDealtToChampions { get; set; }
        public Nullable<short> magicDamageDealtToChampions { get; set; }
        public Nullable<short> physicalDamageDealtToChampions { get; set; }
        public Nullable<short> trueDamageDealtToChampions { get; set; }
        public Nullable<short> totalHeal { get; set; }
        public Nullable<short> totalUnitsHealed { get; set; }
        public Nullable<short> totalDamageTaken { get; set; }
        public Nullable<short> magicalDamageTaken { get; set; }
        public Nullable<short> physicalDamageTaken { get; set; }
        public Nullable<short> trueDamageTaken { get; set; }
        public Nullable<short> goldEarned { get; set; }
        public Nullable<short> goldSpent { get; set; }
        public Nullable<short> turretKills { get; set; }
        public Nullable<short> inhibitorKills { get; set; }
        public Nullable<short> totalMinionsKilled { get; set; }
        public Nullable<short> neutralMinionsKilled { get; set; }
        public Nullable<short> neutralMinionsKilledTeamJungle { get; set; }
        public Nullable<short> neutralMinionsKilledEnemyJungle { get; set; }
        public Nullable<short> totalTimeCrowdControlDealt { get; set; }
        public Nullable<short> champLevel { get; set; }
        public Nullable<short> visionWardsBoughtInGame { get; set; }
        public Nullable<short> sightWardsBoughtInGame { get; set; }
        public Nullable<short> wardsPlaced { get; set; }
        public Nullable<short> wardsKilled { get; set; }
        public Nullable<bool> firstBloodKill { get; set; }
        public Nullable<bool> firstBloodAssist { get; set; }
        public Nullable<bool> firstTowerKill { get; set; }
        public Nullable<bool> firstTowerAssist { get; set; }
        public Nullable<bool> firstInhibitorKill { get; set; }
        public Nullable<bool> firstInhibitorAssist { get; set; }
        public Nullable<int> combatPlayerScore { get; set; }
        public Nullable<int> objectivePlayerScore { get; set; }
        public Nullable<int> totalPlayerScore { get; set; }
        public Nullable<int> totalScoreRank { get; set; }
        public Nullable<short> item2 { get; set; }
    
        public virtual participant participant { get; set; }
    }
}
