//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class team : IEntity
    {
        public int teamId { get; set; }
        public long gameId { get; set; }
        public Nullable<bool> win { get; set; }
        public Nullable<bool> firstBlood { get; set; }
        public Nullable<bool> firstTower { get; set; }
        public Nullable<bool> firstInhibitor { get; set; }
        public Nullable<bool> firstBaron { get; set; }
        public Nullable<bool> firstDragon { get; set; }
        public Nullable<bool> firstRiftHerald { get; set; }
        public Nullable<short> towerKills { get; set; }
        public Nullable<short> inhibitorKills { get; set; }
        public Nullable<short> baronKills { get; set; }
        public Nullable<short> dragonKills { get; set; }
        public Nullable<short> vilemawKills { get; set; }
        public Nullable<short> riftHeraldKills { get; set; }
        public Nullable<short> dominionVictoryScore { get; set; }
    
        public virtual ban ban { get; set; }
        public virtual game game { get; set; }
    }
}
