//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolLib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeline
    {
        public long gameId { get; set; }
        public int participantId { get; set; }
        public Nullable<double> creepsPerMinDeltas_1 { get; set; }
        public Nullable<double> creepsPerMinDeltas_2 { get; set; }
        public Nullable<double> creepsPerMinDeltas_3 { get; set; }
        public Nullable<double> creepsPerMinDeltas_4 { get; set; }
        public Nullable<double> xpPerMinDeltas_1 { get; set; }
        public Nullable<double> xpPerMinDeltas_2 { get; set; }
        public Nullable<double> xpPerMinDeltas_3 { get; set; }
        public Nullable<double> xpPerMinDeltas_4 { get; set; }
        public Nullable<double> goldPerMinDeltas_1 { get; set; }
        public Nullable<double> goldPerMinDeltas_2 { get; set; }
        public Nullable<double> goldPerMinDeltas_3 { get; set; }
        public Nullable<double> goldPerMinDeltas_4 { get; set; }
        public Nullable<double> damageTakenPerMinDeltas_1 { get; set; }
        public Nullable<double> damageTakenPerMinDeltas_2 { get; set; }
        public Nullable<double> damageTakenPerMinDeltas_3 { get; set; }
        public Nullable<double> damageTakenPerMinDeltas_4 { get; set; }
        public string role { get; set; }
        public string lane { get; set; }
        public Nullable<double> csDiffPerMinDeltas_1 { get; set; }
        public Nullable<double> csDiffPerMinDeltas_2 { get; set; }
        public Nullable<double> csDiffPerMinDeltas_3 { get; set; }
        public Nullable<double> csDiffPerMinDeltas_4 { get; set; }
        public Nullable<double> xpDiffPerMinDeltas_1 { get; set; }
        public Nullable<double> xpDiffPerMinDeltas_2 { get; set; }
        public Nullable<double> xpDiffPerMinDeltas_3 { get; set; }
        public Nullable<double> xpDiffPerMinDeltas_4 { get; set; }
        public Nullable<double> damageTakenDiffPerMinDeltas_1 { get; set; }
        public Nullable<double> damageTakenDiffPerMinDeltas_2 { get; set; }
        public Nullable<double> damageTakenDiffPerMinDeltas_3 { get; set; }
        public Nullable<double> damageTakenDiffPerMinDeltas_4 { get; set; }
    
        public virtual participant participant { get; set; }
    }
}
